### ISSUE TITLE
Error while following through the tutorial.

### ISSUE THREAD

**Issue by BhanuD19** [SaiUpadhyayula/spring-reddit-clone#1]
Heya Sai,
I was following your tutorial and in step 2 where we test sending mail, i got stuck in a tight spot. I am sharing the screenshot of the error. Please help me fix this.
The error persists no matter using async or not.

![Screenshot 2020-05-28 at 4 23 50 AM](https://user-images.githubusercontent.com/26822704/83080149-1f13fc80-a09b-11ea-8d3b-8586f2357779.png)
![Screenshot 2020-05-28 at 4 23 48 AM](https://user-images.githubusercontent.com/26822704/83080160-23401a00-a09b-11ea-91d6-413f2ef86b2d.png)
![Screenshot 2020-05-28 at 4 23 18 AM](https://user-images.githubusercontent.com/26822704/83080165-2509dd80-a09b-11ea-8162-6f4f22442d99.png)

**Comment by SaiUpadhyayula** [comment]
Hi,

Thanks for reporting this, please have a look at the commit - https://github.com/SaiUpadhyayula/spring-reddit-clone/commit/33e0d5714467a3d816e4ca892537e637192c669b

When there is a checked exception we have to also log the root cause of the exception, by just using throw new SpringRedditException("....") we are consuming the root cause of the error message.

I fixed it with the above-mentioned commit.

Now you should see what is causing the exception.

**Comment by Puji01** [comment]
I got the same error , so i changed the mail port number in application.properties file ,
spring.mail.port = 465

Hope it helps !!!

**Comment by BhanuD19** [comment]
Yes. I did the same thing by using simplemailsender and logging the error with that one. It got solved.
