### ISSUE TITLE
How to make this in MongoDB instead of MySQL ?

### ISSUE THREAD

**Issue by Raghav-byte** [SaiUpadhyayula/spring-reddit-clone#34]
I was trying to make a database in MySQL but it was showing different errors every time. I have experience in MongoDB so I was thinking of making this in Mongo only instead of MYSQL, can someone guide me on how to do that !! Thanks in advance

**Comment by spencerlepine** [comment]
@Raghav-byte since MongoDB isn't a relational database, it would be a completely different way to structure the data. You would not be able to do `JOIN` queries.

If you are sticking to NoSQL, you could check out a [Digital Ocean tutorial](https://www.digitalocean.com/community/tutorials/spring-boot-mongodb)

or [Spring Boot, MongoDB: JWT Authentication with Spring Security article](https://www.bezkoder.com/spring-boot-jwt-auth-mongodb/) + [GitHub Repository](https://github.com/bezkoder/spring-boot-security-jwt-auth-mongodb)
